# Single Burst Caculation 

This notebook is for pre-implementation for adding the burst datatable to the dashboard

In [1]:
from utilities import *

In [3]:
df = cleanup('/Users/yunyihuang/Desktop/gl_datastream/DataStream/Dashboards/test-data/output_file_test.xlsx')
df

,Subject,Start Datetime,End Datetime,Filename,Experiment,Group,Box,MSN,FR,Active Lever Presses,...,Reward 16,Timeout Press 1,Timeout Press 2,Timeout Press 3,Timeout Press 4,Timeout Press 5,Timeout Press 6,Timeout Press 7,Timeout Press 8,Timeout
0,F1501,2021-11-29 15:14:20,2021-11-29 17:41:30,C:\MED-PC IV\DATA\MTF134BC15HSOXYSHA01,0,0,1,GWAS 2hNEW,0,4.0,...,0.0,283.0,284.0,0.0,0.0,0.0,0.0,0.0,0.0,2
1,F1502,2021-11-29 15:14:24,2021-11-29 17:41:30,MTF134BC15HSOXYSHA01\n,0,0,2,GWAS 2hNEW,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,F1503,2021-11-29 15:14:27,2021-11-29 17:41:30,MTF134BC15HSOXYSHA01\n,0,0,3,GWAS 2hNEW,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,F1504,2021-11-29 15:14:30,2021-11-29 17:41:30,MTF134BC15HSOXYSHA01\n,0,0,4,GWAS 2hNEW,0,10.0,...,0.0,5141.0,5145.0,5168.0,5172.0,0.0,0.0,0.0,0.0,4
4,F1505,2021-11-29 15:14:46,2021-11-29 17:41:30,MTF134BC15HSOXYSHA01\n,0,0,5,GWAS 2hNEW,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
5,F1506,2021-11-29 15:14:49,2021-11-29 17:41:30,MTF134BC15HSOXYSHA01\n,0,0,6,GWAS 2hNEW,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
6,F1507,2021-11-29 15:14:53,2021-11-29 17:41:30,MTF134BC15HSOXYSHA01\n,0,0,7,GWAS 2hNEW,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
7,F1508,2021-11-29 15:39:44,2021-11-29 17:41:30,MTF134BC15HSOXYSHA01\n,0,0,8,GWAS 2hNEW,0,7.0,...,0.0,1187.0,6754.0,0.0,0.0,0.0,0.0,0.0,0.0,2
8,F1509,2021-11-29 15:39:59,2021-11-29 17:41:30,MTF134BC15HSOXYSHA01\n,0,0,9,GWAS 2hNEW,0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
9,F1510,2021-11-29 15:40:05,2021-11-29 17:41:30,MTF134BC15HSOXYSHA01\n,0,0,10,GWAS 2hNEW,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
10,F1511,2021-11-29 15:40:10,2021-11-29 17:41:30,MTF134BC15HSOXYSHA01\n,0,0,11,GWAS 2hNEW,0,4.0,...,0.0,2868.0,2869.0,0.0,0.0,0.0,0.0,0.0,0.0,2
11,F1512,2021-11-29 15:40:14,2021-11-29 17:41:30,MTF134BC15HSOXYSHA01\n,0,0,12,GWAS 2hNEW,0,3.0,...,0.0,5778.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
12,F1513,2021-11-29 15:40:18,2021-11-29 17:41:30,MTF134BC15HSOXYSHA01\n,0,0,13,GWAS 2hNEW,0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
13,F1514,2021-11-29 15:40:22,2021-11-29 17:41:30,MTF134BC15HSOXYSHA01\n,0,0,14,GWAS 2hNEW,0,6.0,...,0.0,2519.0,4878.0,0.0,0.0,0.0,0.0,0.0,0.0,2
14,F1515,2021-11-29 15:40:26,2021-11-29 17:41:30,MTF134BC15HSOXYSHA01\n,0,0,15,GWAS 2hNEW,0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
15,F1516,2021-11-29 15:40:30,2021-11-29 17:41:30,MTF134BC15HSOXYSHA01\n,0,0,16,GWAS 2hNEW,0,24.0,...,6709.0,319.0,322.0,332.0,1647.0,1649.0,5617.0,6704.0,6720.0,8

In [7]:
test = calculations_single(df)
test.columns

Index(['Subject', 'meanInterval', 'stdInterval', 'modeInterval',
       'meanNumRewards', 'numBurst', 'maxBurst', 'pctRewards'],
      dtype='object', name=0)

In [8]:
test.rename(columns = {'meanInterval':'mean Interval', 
                     'stdInterval':'std Interval',
                     'modeInterval':'mode Interval',
                     'meanNumRewards':'mean Num Rewards',
                     'numBurst':'num Burst',
                     'maxBurst':'max Burst',
                     'pctRewards':'pct Rewards',}, 
          inplace = True)

In [9]:
test

,Subject,mean Interval,std Interval,mode Interval,mean Num Rewards,num Burst,max Burst,pct Rewards
0,F1501,257.00,0.00,257.0,0.0,0,0,0.0
1,F1502,NaN,NaN,NaN,0.0,0,0,NaN
2,F1503,NaN,NaN,NaN,0.0,0,0,NaN
3,F1504,1037.20,1996.42,5030.0,4.0,1,4,67.0
4,F1505,NaN,NaN,NaN,0.0,0,0,NaN
5,F1506,NaN,NaN,NaN,0.0,0,0,NaN
6,F1507,NaN,NaN,NaN,0.0,0,0,NaN
7,F1508,1483.50,2317.55,45.0,2.0,2,2,80.0
8,F1509,2838.00,0.00,2838.0,0.0,0,0,0.0
9,F1510,NaN,NaN,NaN,0.0,0,0,NaN
10,F1511,1842.00,0.00,1842.0,0.0,0,0,0.0
11,F1512,37.00,0.00,37.0,2.0,1,2,100.0
12,F1513,NaN,NaN,NaN,0.0,0,0,0.0
13,F1514,804.67,1084.29,24.0,2.0,2,2,100.0
14,F1515,NaN,NaN,NaN,0.0,0,0,0.0
15,F1516,426.27,599.42,20.0,2.5,4,4,62.0