In [1]:
import pandas as pd
import os
from ast import literal_eval

In [8]:
TRIAL_LGA_PATH_A = '/Users/yunyihuang/Desktop/gl_data/TRIAL/COC_LGA'
TRIAL_LGA_PATH_B = '/Users/yunyihuang/Desktop/gl_data/TRIAL/OXY_LGA'
TRIAL_LGA_TEST = ["/Users/yunyihuang/Desktop/gl_data/TRIAL/COC_LGA/BSB273BC08HSLGA01_transformed.csv"]
TRIAL_LGA_FILES = (
    # [os.path.join(TRIAL_LGA_PATH_A, i) for i in sorted(os.listdir(TRIAL_LGA_PATH_A)) if (i != '.DS_Store')] 
    # + 
    [os.path.join(TRIAL_LGA_PATH_B, i) for i in sorted(os.listdir(TRIAL_LGA_PATH_B)) if (i != '.DS_Store')]
)

In [9]:
len(TRIAL_LGA_FILES)

1182

In [3]:
filepath = "/Users/yunyihuang/Desktop/gl_data/TRIAL/COC_LGA/"
coc_files = sorted(os.listdir(filepath))

In [4]:
len(coc_files)

923

In [139]:
test_df = pd.read_csv('/Users/yunyihuang/Desktop/gl_data/TRIAL/COC_SHOCK/BSB273BC08HSSHOCK-1_transformed.csv',index_col=0)
test_df.head()

,rfid,subject,room,cohort,trial_id,drug,box,start_time,end_time,start_date,end_date,total_active_lever_presses,total_inactive_lever_presses,total_shocks,total_reward,rewards_after_first_shock,rewards_got_shock,reward_timestamps
0,933000320046919,F809,BSB273B,8,SHOCK,cocaine,1,10:23:32,11:25:09,2019-08-02,2019-08-02,23,0,6,20,13,"[8, 9, 10, 13, 15, 18, 0, 0, 0, 0, 0, 0, 0, 0,...","[15, 53, 100, 433, 588, 760, 972, 1152, 1250, ..."
1,933000320047108,F810,BSB273B,8,SHOCK,cocaine,2,10:23:37,11:25:09,2019-08-02,2019-08-02,65,2,18,59,53,"[7, 8, 10, 15, 17, 18, 21, 22, 26, 34, 35, 39,...","[4, 126, 146, 173, 231, 270, 299, 432, 458, 53..."
2,933000320047129,F811,BSB273B,8,SHOCK,cocaine,3,10:23:41,11:25:09,2019-08-02,2019-08-02,5,0,1,4,3,"[2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 163, 2432, 3474, 0, 0, 0, 0, 0, 0, 0, 0, 0..."
3,933000320047126,F812,BSB273B,8,SHOCK,cocaine,4,10:23:43,11:25:09,2019-08-02,2019-08-02,1,0,0,1,2,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1718, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,933000320047111,F813,BSB273B,8,SHOCK,cocaine,5,10:23:45,11:25:09,2019-08-02,2019-08-02,36,0,9,32,28,"[5, 7, 8, 18, 19, 20, 26, 27, 29, 0, 0, 0, 0, ...","[1, 25, 56, 80, 105, 126, 155, 181, 201, 409, ..."

In [138]:
print(len(test_df.columns))
test_df.columns

18

Index(['rfid', 'subject', 'room', 'cohort', 'trial_id', 'drug', 'box',
       'start_time', 'end_time', 'start_date', 'end_date',
       'total_active_lever_presses', 'total_inactive_lever_presses',
       'total_shocks', 'total_reward', 'rewards_after_first_shock',
       'rewards_got_shock', 'reward_timestamps'],
      dtype='object')

In [129]:
test_row = test_df.iloc[0]

In [130]:
vals = test_row.get("active_timestamps")
type(vals)

str

In [99]:
def serialize_timestamps(string_of_timestamps):
    timestamp_list = literal_eval(string_of_timestamps)

    while type(timestamp_list[-1]) == list:
        timestamp_list.pop()
    
    if sum(timestamp_list) == 0:
        return "no timestamps"
    
    while timestamp_list[-1] == 0:
        timestamp_list.pop()
    
    lst_strings = [str(i) for i in timestamp_list]
    return " ".join(lst_strings)

In [109]:
lst2 = "[0,1,1,0, [1,2,3]]"
serialize_timestamps(lst2)

'0 1 1'

In [100]:
all_lengths = []

for t in ["active_timestamps", "inactive_timestamps", "reward_timestamps", "timeout_timestamps"]:
    for i in range(len(test_df)):
        test_row = test_df.iloc[i]
        vals = test_row.get(t)
        output_string = serialize_timestamps(vals)
        all_lengths.append(len(output_string))

In [101]:
max(all_lengths)

1059

In [104]:
len(all_lengths)

64

In [ ]:
# max is 1059

In [118]:
len(test_df.columns)

19

In [121]:
test_df.columns.tolist()

['rfid',
 'subject',
 'room',
 'cohort',
 'trial_id',
 'drug',
 'box',
 'start_time',
 'end_time',
 'start_date',
 'end_date',
 'active_lever_presses',
 'inactive_lever_presses',
 'reward_presses',
 'timeout_presses',
 'active_timestamps',
 'inactive_timestamps',
 'reward_timestamps',
 'timeout_timestamps']

In [117]:
test_df[test_df['rfid'] != -999].reset_index(drop=True)

,rfid,subject,room,cohort,trial_id,drug,box,start_time,end_time,start_date,end_date,active_lever_presses,inactive_lever_presses,reward_presses,timeout_presses,active_timestamps,inactive_timestamps,reward_timestamps,timeout_timestamps
0,933000320047477,F801,BSB273B,8,LGA01,cocaine,1,09:16:44,15:42:38,2019-07-11,2019-07-11,113,2,86,30,"[2309, 2316, 2317, 2349, 2410, 2446, 2526, 254...","[2342, 2343, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[2309, 2349, 2410, 2446, 2526, 2546, 2922, 312...","[2316, 2317, 3539, 5848, 5849, 7465, 9309, 107..."
1,933000320047103,F802,BSB273B,8,LGA01,cocaine,2,09:16:49,15:42:38,2019-07-11,2019-07-11,101,8,68,36,"[307, 315, 422, 423, 2693, 2694, 2925, 3242, 3...","[471, 519, 519, 523, 804, 808, 4719, 20603, 0,...","[307, 422, 2693, 2925, 3242, 3472, 3787, 4539,...","[315, 423, 2694, 4783, 4785, 5317, 8143, 8849,..."
2,933000320047470,F803,BSB273B,8,LGA01,cocaine,3,09:16:52,15:42:38,2019-07-11,2019-07-11,5,11,5,3,"[2788, 3120, 4917, 7356, 16818, 0, 0, 0, 0, 0,...","[2805, 2922, 3182, 3183, 3277, 3365, 8349, 164...","[2788, 3120, 4917, 7356, 16818, 0, 0, 0, 0, 0,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,933000320047475,F804,BSB273B,8,LGA01,cocaine,4,09:16:54,15:42:38,2019-07-11,2019-07-11,20,9,16,7,"[4551, 4723, 4729, 6709, 6711, 6859, 8197, 824...","[6854, 11123, 14652, 14672, 14673, 14675, 2044...","[4551, 4723, 6709, 6859, 8197, 8241, 8801, 131...","[4729, 6711, 14688, 19069, 0, 0, 0, 0, 0, 0, 0..."
4,933000320047312,F805,BSB273B,8,LGA01,cocaine,5,09:16:58,15:42:38,2019-07-11,2019-07-11,144,0,127,20,"[100, 166, 166, 167, 188, 213, 492, 516, 628, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[100, 166, 188, 213, 492, 516, 628, 688, 886, ...","[166, 167, 2868, 8858, 12183, 13597, 14155, 14..."
5,933000320047497,F807,BSB273B,8,LGA01,cocaine,7,09:17:14,15:42:38,2019-07-11,2019-07-11,1,9,1,3,"[9737, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[3678, 3679, 3681, 7403, 7406, 7458, 12089, 18...","[9737, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
6,933000320047490,F808,BSB273B,8,LGA01,cocaine,8,09:17:17,15:42:38,2019-07-11,2019-07-11,39,1,32,10,"[3707, 3768, 5724, 8521, 8559, 8954, 10635, 11...","[762, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...","[3707, 3768, 5724, 8521, 8559, 8954, 10635, 11...","[12514, 14140, 15565, 15993, 18188, 18413, 188..."
7,933000320046919,F809,BSB273B,8,LGA01,cocaine,9,09:17:20,15:42:38,2019-07-11,2019-07-11,20,1,15,8,"[6887, 8963, 8969, 8971, 11775, 11776, 11776, ...","[11660, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...","[6887, 8963, 11775, 11805, 11986, 12074, 12207...","[8969, 8971, 11776, 11776, 18781, 0, 0, 0, 0, ..."
8,933000320047108,F810,BSB273B,8,LGA01,cocaine,10,09:17:23,15:42:38,2019-07-11,2019-07-11,1,5,1,3,"[9693, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[11760, 17164, 20411, 20414, 20415, 0, 0, 0, 0...","[9693, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
9,933000320047129,F811,BSB273B,8,LGA01,cocaine,11,09:17:27,15:42:38,2019-07-11,2019-07-11,191,15,129,65,"[467, 474, 503, 814, 856, 956, 1215, 1253, 169...","[187, 320, 321, 365, 509, 517, 553, 908, 1755,...","[467, 503, 814, 856, 956, 1215, 1253, 1690, 18...","[474, 2743, 4271, 4754, 5274, 5630, 5631, 6450..."
10,933000320047126,F812,BSB273B,8,LGA01,cocaine,12,09:17:32,15:42:38,2019-07-11,2019-07-11,160,0,155,8,"[945, 976, 1058, 1094, 1127, 1170, 1308, 1341,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[945, 976, 1058, 1094, 1127, 1170, 1308, 1341,...","[6618, 12178, 19022, 20455, 20923, 0, 0, 0, 0,..."
11,933000320047111,F813,BSB273B,8,LGA01,cocaine,13,09:17:36,15:42:38,2019-07-11,2019-07-11,107,0,105,5,"[219, 243, 287, 328, 349, 399, 438, 648, 921, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[219, 243, 287, 328, 349, 399, 438, 648, 921, ...","[6408, 14892, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,..."
12,933000320047264,F814,BSB273B,8,LGA01,cocaine,14,09:17:38,15:42:38,2019-07-11,2019-07-11,101,0,90,14,"[2902, 2997, 3006, 3012, 3042, 3208, 3232, 344...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[2902, 2997, 3042, 3208, 3232, 3445, 3478, 358...","[3006, 3012, 4114, 4783, 7427, 9293, 10246, 14..."
13,933000320047110,F815,BSB273B,8,LGA01,cocaine,15,09:17:41,15:42:38,2019-07-11,2019-07-11,81,7,49,35,"[9483, 9490, 9515, 12907, 12914, 13004, 13085,...","[3756, 8914, 9440, 9441, 9446, 16103, 16884, 0...","[9483, 9515, 12907, 13004, 13085, 15709, 15774...","[9490, 12914, 13091, 15722, 16089, 16491, 1650..."
14,933000320046923,F816,BSB273B,8,LGA01,cocaine,16,09:17:46,15:42:38,2019-07-11,2019-07-11,73,72,58,18,"[2183, 2320, 2323, 2602, 3141, 3471, 3672, 448...","[2279, 2599, 2605, 3021, 3135, 3156, 3372, 339...","[2183, 2320, 2602, 3141, 3471, 3672, 4487, 467...","[2323, 4752, 6524, 10082, 10084, 14377, 15939,..."