In [4]:
import pandas as pd

In [5]:
filepath = '/Users/yunyihuang/George Lab Dropbox/George_Lab/Team GWAS/1. Cocaine GWAS/Cocaine Irritability/Irritability/all_irritability.xlsx'

In [6]:
df = pd.read_excel(filepath)
df.head()

,rat,rfid,cohort,sex,group,def_bsl_irr_1,agg_bsl_irr_1,irr_bsl_tot_1,irr_bsl_scorer_1,def_bsl_irr_2,...,def_drug_irr_3,agg_drug_irr_3,irr_drug_total_3,irr_drug_scorer_3,def_drug_ave,agg_drug_ave,total_drug_ave,diff_ave_def,diff_ave_agg,diff_ave_total
0,F1,933000120124701,1,F,cocaine,NaN,NaN,NaN,NaN,NaN,...,15.0,11.0,26.0,adam,13.333333,7.333333,20.666667,NaN,NaN,NaN
1,F2,933000120124703,1,F,cocaine,NaN,NaN,NaN,NaN,NaN,...,16.0,4.0,20.0,adam,14.666667,3.000000,17.666667,NaN,NaN,NaN
2,F3,933000120117342,1,F,cocaine,NaN,NaN,NaN,NaN,NaN,...,9.0,15.0,24.0,adam,8.666667,12.666667,21.333333,NaN,NaN,NaN
3,F4,933000120117333,1,F,cocaine,NaN,NaN,NaN,NaN,NaN,...,2.0,3.0,5.0,adam,2.000000,2.333333,4.333333,NaN,NaN,NaN
4,F5,933000120117347,1,F,cocaine,NaN,NaN,NaN,NaN,NaN,...,6.0,0.0,6.0,adam,9.333333,0.000000,9.333333,NaN,NaN,NaN

In [7]:
df.shape

(662, 38)

In [8]:
df.isna().sum()

rat                    0
rfid                   0
cohort                 0
sex                    0
group                  0
def_bsl_irr_1         97
agg_bsl_irr_1         97
irr_bsl_tot_1         91
irr_bsl_scorer_1      97
def_bsl_irr_2         92
agg_bsl_irr_2         92
irr_bsl_total_2       91
irr_bsl_scorer_2      91
def_bsl_irr_3        218
agg_bsl_irr_3        218
irr_bsl_total_3      218
irr_bsl_scorer_3     218
def_bsl_ave           85
agg_bsl_ave           85
total_bsl_ave         85
def_drug_irr_1       218
agg_drug_irr_1       218
irr_drug_tot_1       218
irr_drug_scorer_1    218
def_drug_irr_2       218
agg_drug_irr_2       218
irr_drug_total_2     218
irr_drug_scorer_2    218
def_drug_irr_3       231
agg_drug_irr_3       231
irr_drug_total_3     231
irr_drug_scorer_3    232
def_drug_ave         164
agg_drug_ave         164
total_drug_ave       164
diff_ave_def         222
diff_ave_agg         222
diff_ave_total       222
dtype: int64

In [89]:
df.columns

Index(['rat', 'rfid', 'cohort', 'sex', 'group', 'def_bsl_irr_1',
       'agg_bsl_irr_1', 'irr_bsl_tot_1', 'irr_bsl_scorer_1', 'def_bsl_irr_2',
       'agg_bsl_irr_2', 'irr_bsl_total_2', 'irr_bsl_scorer_2', 'def_bsl_irr_3',
       'agg_bsl_irr_3', 'irr_bsl_total_3', 'irr_bsl_scorer_3', 'def_bsl_ave',
       'agg_bsl_ave', 'total_bsl_ave', 'def_drug_irr_1', 'agg_drug_irr_1',
       'irr_drug_tot_1', 'irr_drug_scorer_1', 'def_drug_irr_2',
       'agg_drug_irr_2', 'irr_drug_total_2', 'irr_drug_scorer_2',
       'def_drug_irr_3', 'agg_drug_irr_3', 'irr_drug_total_3',
       'irr_drug_scorer_3', 'def_drug_ave', 'agg_drug_ave', 'total_drug_ave',
       'diff_ave_def', 'diff_ave_agg', 'diff_ave_total'],
      dtype='object')

In [9]:
for col in df.columns:
    if col in ['rat','sex','group'] or 'scorer' in col:
        df[col] = df[col].fillna('N/A')

In [10]:
df.isna().sum()

rat                    0
rfid                   0
cohort                 0
sex                    0
group                  0
def_bsl_irr_1         97
agg_bsl_irr_1         97
irr_bsl_tot_1         91
irr_bsl_scorer_1       0
def_bsl_irr_2         92
agg_bsl_irr_2         92
irr_bsl_total_2       91
irr_bsl_scorer_2       0
def_bsl_irr_3        218
agg_bsl_irr_3        218
irr_bsl_total_3      218
irr_bsl_scorer_3       0
def_bsl_ave           85
agg_bsl_ave           85
total_bsl_ave         85
def_drug_irr_1       218
agg_drug_irr_1       218
irr_drug_tot_1       218
irr_drug_scorer_1      0
def_drug_irr_2       218
agg_drug_irr_2       218
irr_drug_total_2     218
irr_drug_scorer_2      0
def_drug_irr_3       231
agg_drug_irr_3       231
irr_drug_total_3     231
irr_drug_scorer_3      0
def_drug_ave         164
agg_drug_ave         164
total_drug_ave       164
diff_ave_def         222
diff_ave_agg         222
diff_ave_total       222
dtype: int64

In [11]:
df.rename(columns={'rat':'subject'},inplace=True)

In [12]:
df

,subject,rfid,cohort,sex,group,def_bsl_irr_1,agg_bsl_irr_1,irr_bsl_tot_1,irr_bsl_scorer_1,def_bsl_irr_2,...,def_drug_irr_3,agg_drug_irr_3,irr_drug_total_3,irr_drug_scorer_3,def_drug_ave,agg_drug_ave,total_drug_ave,diff_ave_def,diff_ave_agg,diff_ave_total
0,F1,933000120124701,1,F,cocaine,NaN,NaN,NaN,N/A,NaN,...,15.0,11.0,26.0,adam,13.333333,7.333333,20.666667,NaN,NaN,NaN
1,F2,933000120124703,1,F,cocaine,NaN,NaN,NaN,N/A,NaN,...,16.0,4.0,20.0,adam,14.666667,3.000000,17.666667,NaN,NaN,NaN
2,F3,933000120117342,1,F,cocaine,NaN,NaN,NaN,N/A,NaN,...,9.0,15.0,24.0,adam,8.666667,12.666667,21.333333,NaN,NaN,NaN
3,F4,933000120117333,1,F,cocaine,NaN,NaN,NaN,N/A,NaN,...,2.0,3.0,5.0,adam,2.000000,2.333333,4.333333,NaN,NaN,NaN
4,F5,933000120117347,1,F,cocaine,NaN,NaN,NaN,N/A,NaN,...,6.0,0.0,6.0,adam,9.333333,0.000000,9.333333,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
657,M1184,933000320187306,11,M,naive,4.0,13.0,17.0,kokila,3.0,...,NaN,NaN,NaN,N/A,NaN,NaN,NaN,NaN,NaN,NaN
658,M1185,933000320187176,11,M,naive,0.0,2.0,2.0,kokila,0.0,...,NaN,NaN,NaN,N/A,NaN,NaN,NaN,NaN,NaN,NaN
659,M1186,933000320187318,11,M,naive,0.0,0.0,0.0,kokila,1.0,...,NaN,NaN,NaN,N/A,NaN,NaN,NaN,NaN,NaN,NaN
660,M1187,933000320187313,11,M,naive,4.0,6.0,10.0,kokila,4.0,...,NaN,NaN,NaN,N/A,NaN,NaN,NaN,NaN,NaN,NaN
661,M1188,933000320187200,11,M,naive,3.0,8.0,11.0,kokila,1.0,...,NaN,NaN,NaN,N/A,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df.to_csv('/Users/yunyihuang/George Lab Dropbox/George_Lab/Team GWAS/1. Cocaine GWAS/Cocaine Irritability/Irritability/all_irritability.csv',index=False)

In [14]:
df.shape

(662, 38)

In [18]:
662-645

17